### ISSUE TITLE
index_process' doesn't exist in

### ISSUE THREAD

**Issue by Daseraf** [macopedia/magmi-m2#28]
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'luxpulse.index_process' doesn't exist in /home/luxpulse/public_html/magmi/inc/dbhelper.class.php:233 Stack trace: #0 /home/luxpulse/public_html/magmi/inc/dbhelper.class.php(233): PDOStatement->execute() #1 /home/luxpulse/public_html/magmi/inc/dbhelper.class.php(299): DBHelper->exec_stmt('SELECT indexer_...', NULL, false) #2 /home/luxpulse/public_html/magmi/inc/dbhelper.class.php(341): DBHelper->select('SELECT indexer_...', NULL) #3 /home/luxpulse/public_html/magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(39): DBHelper->selectAll('SELECT indexer_...') #4 /home/luxpulse/public_html/magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(105): Magmi_ReindexingPlugin->initIndexList() #5 /home/luxpulse/public_html/magmi/plugins/base/general/reindex/options_panel.php(20): Magmi_ReindexingPlugin->getIndexList() #6 /home/luxpulse/public_html/magmi/plugins/inc/magmi_plugin.php(95): require('/home/luxpulse/...') #7 in /home/luxpulse/public_html/magmi/inc/dbhelper.class.php on line 233

What wrong?

**Comment by Daseraf** [comment]
After delete all product and reindex - all right.
