### ISSUE TITLE
Getting database connection error using magmi

### ISSUE THREAD

**Issue by poojagirhale** [macopedia/magmi-m2#56]
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in /magmi/inc/dbhelper.class.php:58 Stack trace: #0 /magmi/inc/dbhelper.class.php(58): PDO->__construct('mysql:host=loca...', NULL, NULL, Array) #1 /magmi/inc/magmi_engine.php(528): DBHelper->initDb('localhost', '', NULL, NULL, '3306', NULL, 'net', false) #2 magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(35): Magmi_Engine->connectToMagento() #3 /magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(105): Magmi_ReindexingPlugin->initIndexList() #4 /magmi/plugins/base/general/reindex/options_panel.php(20): Magmi_ReindexingPlugin->getIndexList() #5 /magmi/plugins/inc/magmi_plugin.php(95): require(' in /magmi/inc/dbhelper.class.php on line 58

I have configure magmi with magento 2, but getting this type of error even if my database details are same as in env.php.
Is this magmi version compatible with PHP version 7.0 and what should I do to resolve this type of error.

**Comment by UsmanIftikhar881** [comment]
steps to properly configure magmi in magento2.

1- Put your magmi folder inside pub folder.
2- Create magmi.ini file by modifying magmi.ini.default inside magmi/conf folder.
3- Change the basedir and point it to your pub folder. e.g., basedir="/home/sites/magento2.4_testing.com/pub/magmi"
4- After copying magmi into pub folder. Open pub/magmi/inc/magmi_engine.php and change the else part after line 511 like bellow.

Wrong:
else {
                $host = $this->getProp("DATABASE", "host", "localhost");
                $dbname = $this->getProp("DATABASE", "dbname", "magento");
                $user = $this->getProp("DATABASE", 'root');
                $pass = $this->getProp("DATABASE", 'root');
                $port = $this->getProp("DATABASE", "port", "3306");
            }

Correct:
else {
                $host = $this->getProp("DATABASE", "host", "localhost");
                $dbname = $this->getProp("DATABASE", "dbname", "magento");
                $user = $this->getProp("DATABASE", "username", "root");
                $pass = $this->getProp("DATABASE", "password", "root");
                $port = $this->getProp("DATABASE", "port", "3306");
            }

**Comment by UsmanIftikhar881** [comment]
steps to properly configure magmi in magento2.

1- Put your magmi folder to magento root folder.
2- Create magmi.ini file by modifying magmi.ini.default inside magmi/conf folder.
3- Change the basedir and point it to your pub folder. e.g., basedir="/home/sites/magento2"
4- After copying magmi into your magento root folder. Open magmi/inc/magmi_engine.php file and change the else part after line 511 like bellow.
5- Moreover give proper permissions to you magmi folder.

Wrong:
else {
$host = $this->getProp("DATABASE", "host", "localhost");
$dbname = $this->getProp("DATABASE", "dbname", "magento");
$user = $this->getProp("DATABASE", 'user');
$pass = $this->getProp("DATABASE", 'password');
$port = $this->getProp("DATABASE", "port", "3306");
}

Correct:
else {
$host = $this->getProp("DATABASE", "host", "localhost");
$dbname = $this->getProp("DATABASE", "dbname", "Your DB Name");
$user = $this->getProp("DATABASE", "username", "Your DB User Name");
$pass = $this->getProp("DATABASE", "password", "Your DB Password");
$port = $this->getProp("DATABASE", "port", "3306");
}
