### ISSUE TITLE
Installation Magmi M2

### ISSUE THREAD

**Issue by alaldin** [macopedia/magmi-m2#57]
Hello

I downloaded the M2 extension and after installing it I could not see vM2 in the dropdown menue only M1 v1.9.

What is the best way to install the Magmi M2 on Magento 2.3.2. The wiki installation page is no longer available.

I would be grateful if you can help me.

Love this extension on M1 I hope to get it working on M2.

Thanks

**Comment by tmotyl** [comment]
Hi
Please provide steps/screenshots of what you did.
Did you cloned the repository, or fetched it via composer?

**Comment by alaldin** [comment]
Hello, I downloaded the zip files; I managed to get Magmi to work on M2 but now I get the below error.
I have searched high and low and even changed the db user / pass but still i cant get rid of the error.
How did 

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in /home/aikigailifecom/public_html/magmi/inc/dbhelper.class.php:58 Stack trace: #0 /home/aikigailifecom/public_html/magmi/inc/dbhelper.class.php(58): PDO->__construct('mysql:host=loca...', NULL, NULL, Array) #1 /home/aikigailifecom/public_html/magmi/inc/magmi_engine.php(518): DBHelper->initDb('localhost', 'magento', NULL, NULL, '3306', NULL, 'net', false) #2 /home/aikigailifecom/public_html/magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(35): Magmi_Engine->connectToMagento() #3 /home/aikigailifecom/public_html/magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(105): Magmi_ReindexingPlugin->initIndexList() #4 /home/aikigailifecom/public_html/magmi/plugins/base/general/reindex/options_panel.php(20): Magmi_ReindexingPlugin->getIndexList() #5 /home/aikigailifecom/public_html/magmi/plugins/inc/magmi_plugin.php(95): require('/home/aikigaili...') #6 /home/aikigailifecom/public_html/mag in /home/aikigailifecom/public_html/magmi/inc/dbhelper.class.php on line 58

**Comment by giri-gta-repo** [comment]
Anyone have answer?

**Comment by UsmanIftikhar881** [comment]
steps to properly configure magmi in magento2.

1- Put your magmi folder inside pub folder.
2- Create magmi.ini file by modifying magmi.ini.default inside magmi/conf folder.
3- Change the basedir and point it to your pub folder. e.g., basedir="/home/sites/magento2.4_testing.com/pub/magmi"
4- After copying magmi into pub folder. Open pub/magmi/inc/magmi_engine.php and change the else part after line 511 like bellow.

Wrong:
else {
                $host = $this->getProp("DATABASE", "host", "localhost");
                $dbname = $this->getProp("DATABASE", "dbname", "magento");
                $user = $this->getProp("DATABASE", 'root');
                $pass = $this->getProp("DATABASE", 'root');
                $port = $this->getProp("DATABASE", "port", "3306");
            }

Correct:
else {
                $host = $this->getProp("DATABASE", "host", "localhost");
                $dbname = $this->getProp("DATABASE", "dbname", "magento");
                $user = $this->getProp("DATABASE", "username", "root");
                $pass = $this->getProp("DATABASE", "password", "root");
                $port = $this->getProp("DATABASE", "port", "3306");
            }

**Comment by UsmanIftikhar881** [comment]
steps to properly configure magmi in magento2.

1- Put your magmi folder to magento root folder.
2- Create magmi.ini file by modifying magmi.ini.default inside magmi/conf folder.
3- Change the basedir and point it to your pub folder. e.g., basedir="/home/sites/magento2"
4- After copying magmi into your magento root folder. Open magmi/inc/magmi_engine.php file and change the else part after line 511 like bellow.

Wrong:
else {
$host = $this->getProp("DATABASE", "host", "localhost");
$dbname = $this->getProp("DATABASE", "dbname", "magento");
$user = $this->getProp("DATABASE", 'user');
$pass = $this->getProp("DATABASE", 'password');
$port = $this->getProp("DATABASE", "port", "3306");
}

Correct:
else {
$host = $this->getProp("DATABASE", "host", "localhost");
$dbname = $this->getProp("DATABASE", "dbname", "Your DB Name");
$user = $this->getProp("DATABASE", "username", "Your DB User Name");
$pass = $this->getProp("DATABASE", "password", "Your DB Password");
$port = $this->getProp("DATABASE", "port", "3306");
}
