### ISSUE TITLE
i can't login in the web using magmi:magmi

### ISSUE THREAD

**Issue by hkvega01** [macopedia/magmi-m2#59]
is magmi:magmi still a valid default password?

**Comment by alaldin** [comment]
Hi, I managed to get access to magmi but its giving me the below error.
Please, can you help me fix this error? Thanks

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in /home/aikigailifecom/public_html/magmi/inc/dbhelper.class.php:58 Stack trace: #0 /home/aikigailifecom/public_html/magmi/inc/dbhelper.class.php(58): PDO->__construct('mysql:host=loca...', NULL, NULL, Array) #1 /home/aikigailifecom/public_html/magmi/inc/magmi_engine.php(518): DBHelper->initDb('localhost', 'magento', NULL, NULL, '3306', NULL, 'net', false) #2 /home/aikigailifecom/public_html/magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(35): Magmi_Engine->connectToMagento() #3 /home/aikigailifecom/public_html/magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(105): Magmi_ReindexingPlugin->initIndexList() #4 /home/aikigailifecom/public_html/magmi/plugins/base/general/reindex/options_panel.php(20): Magmi_ReindexingPlugin->getIndexList() #5 /home/aikigailifecom/public_html/magmi/plugins/inc/magmi_plugin.php(95): require('/home/aikigaili...') #6 /home/aikigailifecom/public_html/mag in /home/aikigailifecom/public_html/magmi/inc/dbhelper.class.php on line 58
