### ISSUE TITLE
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password:

### ISSUE THREAD

**Issue by alaldin** [macopedia/magmi-m2#62]
Hello, I downloaded the zip files; I managed to get Magmi to work on M2 but now I get the below error.
I have searched high and low and even changed the db user / pass but still i cant get rid of the error.
How did

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in /home/aikigailifecom/public_html/magmi/inc/dbhelper.class.php:58 Stack trace: #0 /home/aikigailifecom/public_html/magmi/inc/dbhelper.class.php(58): PDO->__construct('mysql:host=loca...', NULL, NULL, Array) #1 /home/aikigailifecom/public_html/magmi/inc/magmi_engine.php(518): DBHelper->initDb('localhost', 'magento', NULL, NULL, '3306', NULL, 'net', false) #2 /home/aikigailifecom/public_html/magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(35): Magmi_Engine->connectToMagento() #3 /home/aikigailifecom/public_html/magmi/plugins/base/general/reindex/magmi_reindexing_plugin.php(105): Magmi_ReindexingPlugin->initIndexList() #4 /home/aikigailifecom/public_html/magmi/plugins/base/general/reindex/options_panel.php(20): Magmi_ReindexingPlugin->getIndexList() #5 /home/aikigailifecom/public_html/magmi/plugins/inc/magmi_plugin.php(95): require('/home/aikigaili...') #6 /home/aikigailifecom/public_html/mag in /home/aikigailifecom/public_html/magmi/inc/dbhelper.class.php on line 58

### Steps to reproduce
// Provide a list of steps to reproduce this bug, include which plugins you use
// You can attach your magmi profile files stored in directory "{your Magento dir}/magmi/conf/{your profile name directory}
1. 
2. 
3. 

### Actual result
// Tell us what happens instead - screenshot, logs etc.
1.

**Comment by serik303** [comment]
google search 
https://magento.stackexchange.com/questions/208225/how-do-i-install-the-magmi-for-magento-2-extension

go to magmi/inc/magmi_engine.php replace the one 511 line and replace else code and add you credential

else {
                $host = $this->getProp("DATABASE", "host", "localhost");
                $dbname = $this->getProp("DATABASE", "dbname", "magento");
                $user = $this->getProp("DATABASE", "user",'root');
                $pass = $this->getProp("DATABASE", "password",'root');
                $port = $this->getProp("DATABASE", "port", "3306");
            }

**Comment by tmotyl** [comment]
Can you please send a pull request?

**Comment by websiteni** [comment]
I tried adding the database credentials to magmi_engine.php, but it didn't make any different.  I'm still getting this error
